
image: ruby:3.3.8
before_script:
- gem install async pdf-reader rspec httpx concurrent-ruby async-http telegem rubocop bundle install
test:
  script:
  - rspec test/spec.rb
stages:
- test
include:
- template: Security/SAST-IaC.latest.gitlab-ci.yml
