name: telegem-release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Keeps the manual button just in case

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to check version history
      packages: write # Needed for GitHub Packages

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Allows us to compare with the previous commit

      - name: Check for version bump
        id: check_version
        run: |
          VERSION_FILE=$(find lib -name "version.rb")
          OLD_VER=$(git show HEAD~1:$VERSION_FILE | grep "VERSION =" | cut -d '"' -f 2 | cut -d "'" -f 2)
          NEW_VER=$(grep "VERSION =" $VERSION_FILE | cut -d '"' -f 2 | cut -d "'" -f 2)
          
          if [ "$OLD_VER" != "$NEW_VER" ]; then
            echo "Version bumped to $NEW_VER"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No version change."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Ruby 3.2
        if: steps.check_version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Publish to GPR
        if: steps.check_version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p $HOME/.gem
          printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}

      - name: Publish to RubyGems
        if: steps.check_version.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          printf -- ":rubygems_api_key: ${RUBYGEMS_KEY}\n" >> $HOME/.gem/credentials
          gem push *.gem
        env:
          RUBYGEMS_KEY: "${{ secrets.RUBYGEMS_AUTH_TOKEN }}"
